# Generated by Django 6.0.2 on 2026-05-11 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_follow_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitabilityCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnl_7d', models.FloatField(default=0.0)),
                ('pnl_30d', models.FloatField(default=0.0)),
                ('pnl_all', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profitability', to='accounts.walletuser')),
            ],
        ),
    ]
