# Generated by Django 6.0.2 on 2026-05-31 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_walletuser_rep_energy'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletuser',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
