# Generated by Django 6.0.2 on 2026-05-31 20:02

from django.db import migrations


def populate_usernames(apps, schema_editor):
    WalletUser = apps.get_model('accounts', 'WalletUser')
    for user in WalletUser.objects.filter(username__isnull=True):
        base_username = user.address[:6]
        username = base_username
        
        counter = 1
        while WalletUser.objects.filter(username__iexact=username).exclude(pk=user.pk).exists():
            username = f"{base_username}_{counter}"
            counter += 1
            
        user.username = username
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_walletuser_username'),
    ]

    operations = [
        migrations.RunPython(populate_usernames, reverse_code=migrations.RunPython.noop),
    ]
