# Generated by Django 6.0.2 on 2026-05-31 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_populate_usernames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletuser',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
