# Generated by Django 6.0.2 on 2026-06-06 19:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_walletuser_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="walletuser",
            name="avatar",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="avatar"
            ),
        ),
    ]
