# Generated by Codex on 2026-06-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_walletuser_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("username_updated", "Username updated"),
                            ("post_created", "Post created"),
                            ("post_deleted", "Post deleted"),
                        ],
                        max_length=32,
                    ),
                ),
                ("summary", models.CharField(max_length=160)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="profile_changelog_actions",
                        to="accounts.walletuser",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changelog_entries",
                        to="accounts.walletuser",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="profilechangelog",
            index=models.Index(
                fields=["user", "-created_at"],
                name="profile_changelog_user_idx",
            ),
        ),
    ]
