# Generated by Django 6.0.2 on 2026-06-06 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_profilechangelog"),
        ("accounts", "0009_walletuser_avatar"),
    ]

    operations = []
