# Generated by Django 6.0.2 on 2026-06-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_merge_0009_profilechangelog_0009_walletuser_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="walletuser",
            name="phone_e164",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
