"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env from backend/ if present (local development).
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-dev-only-change-me-in-env",
)

DEBUG = os.environ.get("DJANGO_DEBUG", "True").lower() == "true"

ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    if h.strip()
]
# Render sets this automatically; append so deploy works without hardcoding the hostname.
_render_host = os.environ.get("RENDER_EXTERNAL_HOSTNAME", "").strip()
if _render_host and _render_host not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(_render_host)

def _parse_origins(raw: str, default: str) -> list[str]:
    """Parse comma-separated origins; strip whitespace and trailing slashes."""
    origins = []
    for o in os.environ.get(raw, default).split(","):
        o = o.strip().rstrip("/")
        if o:
            origins.append(o)
    return origins


CORS_ALLOWED_ORIGINS = _parse_origins(
    "CORS_ALLOWED_ORIGINS",
    "http://localhost:5173,http://127.0.0.1:5173",
)

# Local development convenience: accept any localhost / 127.0.0.1 port so the
# Vite dev server works whether it's reached via "localhost" or "127.0.0.1" and
# regardless of which fallback port it picks (5173, 5174, …).
if DEBUG:
    CORS_ALLOWED_ORIGIN_REGEXES = [
        r"^http://localhost:\d+$",
        r"^http://127\.0\.0\.1:\d+$",
    ]

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party
    "rest_framework",
    "corsheaders",
    "cloudinary_storage",
    "cloudinary",
    # Local
    "accounts",
    "posts",
    "notifications",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

_default_db = f"sqlite:///{BASE_DIR / 'db.sqlite3'}"
_database_url = os.environ.get("DATABASE_URL", _default_db)
_use_ssl = not DEBUG and _database_url.startswith(
    ("postgres://", "postgresql://")
)

DATABASES = {
    "default": dj_database_url.config(
        default=_default_db,
        conn_max_age=600,
        ssl_require=_use_ssl,
    )
}

# Bound the time spent on a single connection attempt so a suspended Neon
# compute (cold start) fails fast and is retried, rather than hanging until the
# default OS-level timeout. Only applies to Postgres.
if _database_url.startswith(("postgres://", "postgresql://")):
    DATABASES["default"].setdefault("OPTIONS", {}).setdefault("connect_timeout", 10)

# Always use a local in-memory SQLite DB for `manage.py test`, regardless of
# DATABASE_URL in .env (Neon/Postgres makes the suite slow or appear hung).
if "test" in sys.argv:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": ":memory:",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Media files (user uploads) — stored on Cloudinary because Render's free tier
# has an ephemeral filesystem that wipes local uploads on every redeploy.
# The cloudinary SDK and django-cloudinary-storage both auto-configure from the
# CLOUDINARY_URL env var: cloudinary://<api_key>:<api_secret>@<cloud_name>
CLOUDINARY_URL = os.environ.get("CLOUDINARY_URL", "").strip()
DEFAULT_FILE_STORAGE = "cloudinary_storage.storage.MediaCloudinaryStorage"
if not CLOUDINARY_URL:
    import warnings

    warnings.warn(
        "CLOUDINARY_URL is not set; image uploads (post images, avatars) will fail.",
        stacklevel=1,
    )

# Admin wallet addresses — only these can change HardClaim status
_DEFAULT_ADMIN = "0x8C66A1aBF7C949004aF7dE80A3fc0F691538ea74"
ADMIN_ADDRESSES: list[str] = [
    a.strip()
    for a in os.environ.get("ADMIN_ADDRESSES", _DEFAULT_ADMIN).split(",")
    if a.strip()
]

# Twelve Data API key for stock/forex/commodity OHLC fallback (free tier: 800 calls/day)
TWELVE_DATA_API_KEY = os.environ.get("TWELVE_DATA_API_KEY", "").strip()
if not TWELVE_DATA_API_KEY:
    if DEBUG:
        TWELVE_DATA_API_KEY = "4117d86e953d4430bfc7003d72d9ed97"
    else:
        import warnings

        warnings.warn(
            "TWELVE_DATA_API_KEY is not set; stock/forex OHLC fallback will fail.",
            stacklevel=1,
        )

# Observer Pattern: how often the price updater runs (in minutes)
# Used as a reference for the scheduler (cron / Render cron); not enforced in code.
PRICE_UPDATE_INTERVAL_MINUTES = 10

# Django REST Framework
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}

# Simple JWT
from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=7),
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "AUTH_HEADER_TYPES": ("Bearer",),
}
