from django.urls import path
from .views import (
    HardClaimView, HardClaimDetailView, HardClaimResolveView, HardClaimChartDataView,
    PostListCreateView, PostDetailView, ExtractClaimsView, AssetListView,
    ChannelListView, ChannelDetailView, ChannelJoinView, ChannelApproveView, ChannelBanView, ChannelBannedListView,
    ChannelMemberListView, PositionListCreateView, PositionCloseView, PositionResolveView,
    HardClaimMarketView, HardClaimMarketCreateView, HardClaimMarketBuyView, HardClaimMarketPreviewView,
    HardClaimProofView, PositionProofView, ChannelModeratorView, PostDeleteView,
    PositionChartDataView,
)
from .og import HardClaimOGView, PositionOGView

urlpatterns = [
    path("", PostListCreateView.as_view(), name="post-list-create"),
    path("<int:pk>/", PostDetailView.as_view(), name="post-detail"),
    path("<int:pk>/delete/", PostDeleteView.as_view(), name="post-delete"),
    path("extract-claims/", ExtractClaimsView.as_view(), name="extract-claims"),
    path("hard-claims/", HardClaimView.as_view(), name="hard-claims"),
    path("hard-claims/<int:pk>/", HardClaimDetailView.as_view(), name="hard-claim-detail"),
    path("hard-claims/<int:pk>/update-status/", HardClaimView.as_view(), name="hard-claim-update-status"),
    path("hard-claims/<int:pk>/resolve/", HardClaimResolveView.as_view(), name="hard-claim-resolve"),
    path("hard-claims/<int:pk>/chart-data/", HardClaimChartDataView.as_view(), name="hard-claim-chart-data"),
    path("hard-claims/<int:pk>/proof/", HardClaimProofView.as_view(), name="hard-claim-proof"),
    path("hard-claims/<int:pk>/og/", HardClaimOGView.as_view(), name="hard-claim-og"),
    path("hard-claims/<int:pk>/market/", HardClaimMarketView.as_view(), name="hard-claim-market"),
    path("hard-claims/<int:pk>/market/create/", HardClaimMarketCreateView.as_view(), name="hard-claim-market-create"),
    path("hard-claims/<int:pk>/market/buy/", HardClaimMarketBuyView.as_view(), name="hard-claim-market-buy"),
    path("hard-claims/<int:pk>/market/preview/", HardClaimMarketPreviewView.as_view(), name="hard-claim-market-preview"),
    path("assets/", AssetListView.as_view(), name="assets-list"),
    path("channels/", ChannelListView.as_view(), name="channel-list"),
    path("channels/<int:pk>/", ChannelDetailView.as_view(), name="channel-detail"),
    path("channels/<int:pk>/join/", ChannelJoinView.as_view(), name="channel-join"),
    path("channels/<int:pk>/approve/<str:user_address>/", ChannelApproveView.as_view(), name="channel-approve"),
    path("channels/<int:pk>/ban/<str:user_address>/", ChannelBanView.as_view(), name="channel-ban"),
    path("channels/<int:pk>/banned/", ChannelBannedListView.as_view(), name="channel-banned"),
    path("channels/<int:pk>/members/", ChannelMemberListView.as_view(), name="channel-members"),
    path("channels/<int:pk>/moderator/<str:user_address>/", ChannelModeratorView.as_view(), name="channel-moderator"),
    path("positions/", PositionListCreateView.as_view(), name="position-list-create"),
    path("positions/<int:pk>/close/", PositionCloseView.as_view(), name="position-close"),
    path("positions/<int:pk>/resolve/", PositionResolveView.as_view(), name="position-resolve"),
    path("positions/<int:pk>/proof/", PositionProofView.as_view(), name="position-proof"),
    path("positions/<int:pk>/og/", PositionOGView.as_view(), name="position-og"),
    path("positions/<int:pk>/chart-data/", PositionChartDataView.as_view(), name="position-chart-data"),
]
