# Generated by Django 6.0.2 on 2026-03-25 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='HardClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('direction', models.CharField(blank=True, default='', max_length=20)),
                ('until', models.DateField()),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('undetermined', 'Undetermined'), ('rejected', 'Rejected')], default='undetermined', max_length=12)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.asset')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
            ],
        ),
    ]
