# Generated by Django 6.0.2 on 2026-03-25 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_asset_hardclaim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hardclaim',
            name='post',
        ),
    ]
