# Generated by Django 6.0.2 on 2026-03-26 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('posts', '0003_remove_hardclaim_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardclaim',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hard_claims', to='accounts.walletuser'),
        ),
    ]
