# Generated by Django 6.0.2 on 2026-03-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_populate_assets'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardclaim',
            name='percentage',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
