# Generated by Django 6.0.2 on 2026-03-27 16:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_assign_hardclaim_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardclaim',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
