# Generated by Django 6.0.2 on 2026-04-07 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_hardclaim_until_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardclaim',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
