# Generated by Django 6.0.2 on 2026-04-14 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_asset_resolution_metadata'),
        ('posts', '0011_remove_hardclaim_text_required'),
    ]

    operations = [
    ]
