# Generated by Django 6.0.2 on 2026-04-14 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_merge_20260414_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardclaim',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hard_claims', to='posts.post'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='market_type',
            field=models.CharField(choices=[('crypto', 'Crypto'), ('forex', 'Forex'), ('commodity', 'Commodity'), ('equity', 'Equity'), ('index', 'Index')], default='crypto', max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='provider',
            field=models.CharField(choices=[('coingecko', 'Coingecko'), ('yfinance', 'Yfinance')], default='coingecko', max_length=20),
        ),
    ]
