# Generated by Django 6.0.2 on 2026-04-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_merge_20260414_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hardclaim',
            name='text',
        ),
        migrations.AlterField(
            model_name='asset',
            name='market_type',
            field=models.CharField(choices=[('crypto', 'Crypto'), ('forex', 'Forex'), ('commodity', 'Commodity'), ('equity', 'Equity'), ('index', 'Index')], default='crypto', max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='provider',
            field=models.CharField(choices=[('coingecko', 'Coingecko'), ('yfinance', 'Yfinance')], default='coingecko', max_length=20),
        ),
    ]
