# Generated by Django 6.0.2 on 2026-04-14 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_add_post_fk_to_hardclaim'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardClaimEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('creation', 'Creation'), ('price_check', 'Price Check'), ('resolution', 'Resolution')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('hard_claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='posts.hardclaim')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
