# Generated by Django 6.0.2 on 2026-04-14 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_remove_hardclaim_text_alter_asset_market_type_and_more'),
        ('posts', '0014_hardclaimevent'),
    ]

    operations = [
    ]
