# Generated by Django 6.0.2 on 2026-04-15 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_merge_20260414_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='binance_symbol',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='asset',
            name='kraken_pair',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='asset',
            name='kucoin_symbol',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='asset',
            name='twelvedata_symbol',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='provider',
            field=models.CharField(choices=[('coingecko', 'Coingecko'), ('yfinance', 'Yfinance'), ('binance', 'Binance'), ('kucoin', 'Kucoin'), ('kraken', 'Kraken'), ('twelvedata', 'Twelvedata')], default='coingecko', max_length=20),
        ),
        migrations.CreateModel(
            name='OHLCData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ohlc_data', to='posts.asset')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('asset', 'date')},
            },
        ),
    ]
