# Generated by GPT-5.2 on 2026-05-11

from django.db import migrations


def backfill_exchange_symbols(apps, schema_editor):
    Asset = apps.get_model("posts", "Asset")

    mappings = {
        "BTC": {
            "binance_symbol": "BTCUSDT",
            "kucoin_symbol": "BTC-USDT",
            "kraken_pair": "XBTUSD",
        },
        "ETH": {
            "binance_symbol": "ETHUSDT",
            "kucoin_symbol": "ETH-USDT",
            "kraken_pair": "ETHUSD",
        },
    }

    for symbol, values in mappings.items():
        Asset.objects.filter(symbol=symbol).update(**values)


def reverse_backfill_exchange_symbols(apps, schema_editor):
    Asset = apps.get_model("posts", "Asset")
    Asset.objects.filter(symbol__in=["BTC", "ETH"]).update(
        binance_symbol="",
        kucoin_symbol="",
        kraken_pair="",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0016_asset_binance_symbol_asset_kraken_pair_and_more"),
    ]

    operations = [
        migrations.RunPython(
            backfill_exchange_symbols,
            reverse_code=reverse_backfill_exchange_symbols,
        ),
    ]

