# Generated by Django 6.0.2 on 2026-05-11 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_backfill_exchange_symbols_for_btc_eth'),
        ('posts', '0017_community_hardclaim_community_post_community_and_more'),
    ]

    operations = [
    ]
