# Generated by Django 6.0.2 on 2026-05-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_merge_20260511_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='post_permission',
            field=models.CharField(choices=[('all', 'All'), ('creator_only', 'Creator Only')], default='all', max_length=15),
        ),
    ]
