# Generated by Django 6.0.2 on 2026-05-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_community_post_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitymembership',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('banned', 'Banned')], default='pending', max_length=10),
        ),
    ]
