# Generated by Django 6.0.2 on 2026-05-11 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_follow_options'),
        ('posts', '0020_alter_communitymembership_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], max_length=10)),
                ('entry_price', models.FloatField()),
                ('entry_interval', models.DateTimeField()),
                ('stop_loss', models.FloatField()),
                ('take_profit', models.FloatField()),
                ('lifetime', models.DateTimeField()),
                ('exit_price', models.FloatField(blank=True, null=True)),
                ('pnl_percentage', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('missed', 'Missed'), ('active', 'Active'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('closed_early', 'Closed Early')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.asset')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='accounts.walletuser')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='posts.community')),
            ],
        ),
        migrations.CreateModel(
            name='PositionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('creation', 'Creation'), ('entry_triggered', 'Entry Triggered'), ('price_check', 'Price Check'), ('resolution', 'Resolution'), ('manual_close', 'Manual Close')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='posts.position')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
