# Generated by Django 6.0.2 on 2026-05-14 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_merge_20260511_1601'),
        ('posts', '0021_position_positionevent'),
    ]

    operations = [
    ]
