# Generated by Django 6.0.2 on 2026-05-14 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_merge_20260514_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='last_price_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AssetSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='posts.asset')),
                ('position', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asset_subscription', to='posts.position')),
            ],
        ),
    ]
