# Generated by Django 6.0.2 on 2026-05-17 19:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_asset_last_price_update_assetsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='ohlcdata',
            name='interval',
            field=models.CharField(default='1d', max_length=5),
        ),
        migrations.AddField(
            model_name='ohlcdata',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name='ohlcdata',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterUniqueTogether(
            name='ohlcdata',
            unique_together={('asset', 'timestamp', 'interval')},
        ),
        migrations.RemoveField(
            model_name='ohlcdata',
            name='date',
        ),
    ]
