# Generated by Django 6.0.2 on 2026-05-27 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_walletuser_rep_energy"),
        ("posts", "0024_alter_ohlcdata_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClaimMarket",
            fields=[
                (
                    "hard_claim",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="market",
                        serialize=False,
                        to="posts.hardclaim",
                    ),
                ),
                ("y_reserve", models.FloatField()),
                ("n_reserve", models.FloatField()),
                ("yes_outstanding", models.FloatField(default=0.0)),
                ("no_outstanding", models.FloatField(default=0.0)),
                ("escrow", models.FloatField(default=0.0)),
                ("total_burned", models.FloatField(default=0.0)),
                (
                    "creator_side",
                    models.CharField(
                        choices=[("YES", "Yes"), ("NO", "No")], max_length=3
                    ),
                ),
                ("creator_stake_rep", models.FloatField()),
                ("listing_fee_burned", models.FloatField(default=2.0)),
                ("resolved", models.BooleanField(default=False)),
                ("refunded_trivial", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ClaimStake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[("YES", "Yes"), ("NO", "No")], max_length=3
                    ),
                ),
                ("rep_paid_gross", models.FloatField()),
                ("rep_paid_net", models.FloatField()),
                ("shares", models.FloatField()),
                ("entry_price", models.FloatField()),
                ("is_creator", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stakes",
                        to="posts.claimmarket",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claim_stakes",
                        to="accounts.walletuser",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "unique_together": {("market", "user")},
            },
        ),
    ]
