# Generated by Django 6.0.2 on 2026-05-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_walletuser_rep_energy"),
        ("posts", "0025_claimmarket_claimstake"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="communitymembership",
            index=models.Index(
                fields=["community", "status"], name="comm_member_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hardclaim",
            index=models.Index(
                condition=models.Q(("status", "undetermined")),
                fields=["status", "until"],
                name="hardclaim_resolve_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="hardclaim",
            index=models.Index(fields=["author", "-id"], name="hardclaim_author_idx"),
        ),
        migrations.AddIndex(
            model_name="hardclaimevent",
            index=models.Index(
                fields=["hard_claim", "event_type"], name="hardclaim_event_lookup_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                condition=models.Q(("community__isnull", True)),
                fields=["-created_at"],
                name="post_global_feed_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["community", "-created_at"], name="post_community_feed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["author", "-created_at"], name="post_author_feed_idx"
            ),
        ),
    ]
