# Generated by Django 6.0.2 on 2026-05-31 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0027_backfill_crypto_ohlc_symbols'),
        ('posts', '0027_hardclaim_value_type_payda'),
    ]

    operations = [
    ]
