# Generated by Django 6.0.2 on 2026-05-31 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0027_backfill_crypto_ohlc_symbols'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardclaim',
            name='claim_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='hardclaim',
            name='signature',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='position',
            name='position_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='position',
            name='signature',
            field=models.TextField(blank=True, default=''),
        ),
    ]
