# Generated by Django 6.0.2 on 2026-06-01 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0028_add_signature_fields'),
        ('posts', '0029_hardclaim_value_type_payda'),
    ]

    operations = [
    ]
