# Generated by Django 6.0.2 on 2026-06-01 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0029_hardclaim_value_type_payda'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitymembership',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('moderator', 'Moderator'), ('owner', 'Owner')], default='member', max_length=15),
        ),
    ]
