# Generated by Django 6.0.2 on 2026-06-02 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_walletuser_username'),
        ('posts', '0030_add_membership_role'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='communitymembership',
            unique_together=set(),
        ),
        migrations.RemoveIndex(
            model_name='communitymembership',
            name='comm_member_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='post_community_feed_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='post_global_feed_idx',
        ),
        migrations.RenameModel(
            old_name='Community',
            new_name='Channel',
        ),
        migrations.RenameModel(
            old_name='CommunityMembership',
            new_name='ChannelMembership',
        ),
        migrations.RenameField(
            model_name='channelmembership',
            old_name='community',
            new_name='channel',
        ),
        migrations.RenameField(
            model_name='hardclaim',
            old_name='community',
            new_name='channel',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='community',
            new_name='channel',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='community',
            new_name='channel',
        ),
        migrations.AlterField(
            model_name='channel',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_channels', to='accounts.walletuser'),
        ),
        migrations.AlterField(
            model_name='channelmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_memberships', to='accounts.walletuser'),
        ),
        migrations.AlterUniqueTogether(
            name='channelmembership',
            unique_together={('channel', 'user')},
        ),
        migrations.AddIndex(
            model_name='channelmembership',
            index=models.Index(fields=['channel', 'status'], name='chan_member_status_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['channel', '-created_at'], name='post_channel_feed_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(condition=models.Q(('channel__isnull', True)), fields=['-created_at'], name='post_global_feed_idx'),
        ),
    ]
