# Generated by Django 6.0.2 on 2026-06-02 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0031_backfill_all_whitelist_symbols'),
        ('posts', '0031_channel_channelmembership_remove_community_creator_and_more'),
    ]

    operations = [
    ]
