# Generated by Django 6.0.2 on 2026-06-06 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0033_hardclaim_reference_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Claim',
        ),
    ]
