# Generated by Django 6.0.2 on 2026-06-06 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0034_delete_claim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hardclaim',
            name='payda',
        ),
    ]
