# Generated by Django 6.0.2 on 2026-06-06 12:50

from django.db import migrations

def remove_unused_assets(apps, schema_editor):
    Asset = apps.get_model('posts', 'Asset')
    Asset.objects.exclude(symbol__in=["BTC", "ETH", "TRY", "USD"]).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0035_remove_hardclaim_payda'),
    ]

    operations = [
        migrations.RunPython(remove_unused_assets, reverse_code=migrations.RunPython.noop),
    ]
