# Generated by Django 6.0.2 on 2026-06-06 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0036_remove_unused_assets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='privacy_type',
        ),
    ]
