# Generated by Django 6.0.2 on 2026-06-06 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0037_remove_channel_privacy_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='posts.post'),
        ),
        migrations.AlterField(
            model_name='position',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='posts.channel'),
        ),
    ]
