# Generated by Django 6.0.2 on 2026-06-06 19:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0037_remove_channel_privacy_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
