# Generated by Django 6.0.2 on 2026-06-06 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0038_position_post_fk"),
        ("posts", "0038_post_image"),
    ]

    operations = []
