# Generated by Django 6.0.2 on 2026-06-06 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_profilechangelog"),
        ("posts", "0038_postcomment_postlike_savedproof"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostCommentLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="postcomment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="posts.postcomment",
            ),
        ),
        migrations.AddIndex(
            model_name="postcomment",
            index=models.Index(
                fields=["parent", "created_at"], name="post_comment_reply_idx"
            ),
        ),
        migrations.AddField(
            model_name="postcommentlike",
            name="comment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="posts.postcomment",
            ),
        ),
        migrations.AddField(
            model_name="postcommentlike",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_comment_likes",
                to="accounts.walletuser",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="postcommentlike",
            unique_together={("comment", "user")},
        ),
    ]
