# Generated by Django 6.0.2 on 2026-06-06 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0039_merge_0038_position_post_fk_0038_post_image"),
        ("posts", "0039_postcommentlike_postcomment_parent_and_more"),
    ]

    operations = []
