# Generated by Django 6.0.2 on 2026-06-06 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0039_merge_0038_position_post_fk_0038_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
