# Generated by Django 6.0.2 on 2026-06-06 22:14

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0040_merge_20260606_2210"),
    ]

    operations = [
        migrations.AddField(
            model_name="postcomment",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="postcomment",
            name="content",
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
