# Generated by Django 6.0.2 on 2026-06-06 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0040_channel_is_active'),
        ('posts', '0041_postcomment_image_alter_postcomment_content'),
    ]

    operations = [
    ]
