# Generated by Django 6.0.2 on 2026-06-08 09:58

from django.db import migrations, models
from django.db.models import Count


def backfill_usage(apps, schema_editor):
    """Seed usage_count from existing claims + positions so the 'most used'
    ordering is meaningful from day one."""
    Asset = apps.get_model("posts", "Asset")
    HardClaim = apps.get_model("posts", "HardClaim")
    Position = apps.get_model("posts", "Position")
    counts: dict[int, int] = {}
    for model in (HardClaim, Position):
        for row in model.objects.values("asset_id").annotate(n=Count("id")):
            if row["asset_id"] is not None:
                counts[row["asset_id"]] = counts.get(row["asset_id"], 0) + row["n"]
    for asset_id, n in counts.items():
        Asset.objects.filter(pk=asset_id).update(usage_count=n)


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0042_merge_20260607_0234"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="usage_count",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.RunPython(backfill_usage, migrations.RunPython.noop),
    ]
