# Generated by Django 6.0.2 on 2026-06-08 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0042_merge_20260607_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetsubscription',
            name='hard_claim',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_subscription', to='posts.hardclaim'),
        ),
        migrations.AlterField(
            model_name='assetsubscription',
            name='position',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_subscription', to='posts.position'),
        ),
        migrations.AddConstraint(
            model_name='assetsubscription',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('hard_claim__isnull', True), ('position__isnull', False)), models.Q(('hard_claim__isnull', False), ('position__isnull', True)), _connector='OR'), name='subscription_target_exclusive'),
        ),
    ]
