# Generated by Django 6.0.2 on 2026-06-08 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0043_asset_usage_count"),
        ("posts", "0043_assetsubscription_hard_claim_and_more"),
    ]

    operations = []
